// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatmessage.proto

package com.snh.chat.protobuf;

public final class ChatMessageProto {
  private ChatMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.snh.chat.protobuf.proto.ChatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 action = 1;</code>
     *
     * <pre>
     *消息类型 0-普通消息/回复消息 1-系统消息  2-加入群组 3-离开群组
     * </pre>
     */
    boolean hasAction();
    /**
     * <code>optional int32 action = 1;</code>
     *
     * <pre>
     *消息类型 0-普通消息/回复消息 1-系统消息  2-加入群组 3-离开群组
     * </pre>
     */
    int getAction();

    /**
     * <code>optional string uuid = 2;</code>
     *
     * <pre>
     *"S-" + UUID.randomUUID() 系统消息
     *"U-{userId}-{groupId}"+UUID.randomUUID() 用户消息
     * </pre>
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 2;</code>
     *
     * <pre>
     *"S-" + UUID.randomUUID() 系统消息
     *"U-{userId}-{groupId}"+UUID.randomUUID() 用户消息
     * </pre>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 2;</code>
     *
     * <pre>
     *"S-" + UUID.randomUUID() 系统消息
     *"U-{userId}-{groupId}"+UUID.randomUUID() 用户消息
     * </pre>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional string userId = 3;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>optional string userId = 3;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    java.lang.String getUserId();
    /**
     * <code>optional string userId = 3;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional string groupId = 4;</code>
     *
     * <pre>
     *群组ID
     * </pre>
     */
    boolean hasGroupId();
    /**
     * <code>optional string groupId = 4;</code>
     *
     * <pre>
     *群组ID
     * </pre>
     */
    java.lang.String getGroupId();
    /**
     * <code>optional string groupId = 4;</code>
     *
     * <pre>
     *群组ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <code>optional string nickname = 5;</code>
     *
     * <pre>
     *昵称
     * </pre>
     */
    boolean hasNickname();
    /**
     * <code>optional string nickname = 5;</code>
     *
     * <pre>
     *昵称
     * </pre>
     */
    java.lang.String getNickname();
    /**
     * <code>optional string nickname = 5;</code>
     *
     * <pre>
     *昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <code>optional string pic = 6;</code>
     *
     * <pre>
     *用户头像
     * </pre>
     */
    boolean hasPic();
    /**
     * <code>optional string pic = 6;</code>
     *
     * <pre>
     *用户头像
     * </pre>
     */
    java.lang.String getPic();
    /**
     * <code>optional string pic = 6;</code>
     *
     * <pre>
     *用户头像
     * </pre>
     */
    com.google.protobuf.ByteString
        getPicBytes();

    /**
     * <code>optional string content = 7;</code>
     *
     * <pre>
     *消息文字内容
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 7;</code>
     *
     * <pre>
     *消息文字内容
     * </pre>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 7;</code>
     *
     * <pre>
     *消息文字内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>optional string pictures = 8;</code>
     *
     * <pre>
     *图片
     * </pre>
     */
    boolean hasPictures();
    /**
     * <code>optional string pictures = 8;</code>
     *
     * <pre>
     *图片
     * </pre>
     */
    java.lang.String getPictures();
    /**
     * <code>optional string pictures = 8;</code>
     *
     * <pre>
     *图片
     * </pre>
     */
    com.google.protobuf.ByteString
        getPicturesBytes();

    /**
     * <code>optional string videos = 9;</code>
     *
     * <pre>
     *视频
     * </pre>
     */
    boolean hasVideos();
    /**
     * <code>optional string videos = 9;</code>
     *
     * <pre>
     *视频
     * </pre>
     */
    java.lang.String getVideos();
    /**
     * <code>optional string videos = 9;</code>
     *
     * <pre>
     *视频
     * </pre>
     */
    com.google.protobuf.ByteString
        getVideosBytes();

    /**
     * <code>optional string audios = 10;</code>
     *
     * <pre>
     *音频
     * </pre>
     */
    boolean hasAudios();
    /**
     * <code>optional string audios = 10;</code>
     *
     * <pre>
     *音频
     * </pre>
     */
    java.lang.String getAudios();
    /**
     * <code>optional string audios = 10;</code>
     *
     * <pre>
     *音频
     * </pre>
     */
    com.google.protobuf.ByteString
        getAudiosBytes();

    /**
     * <code>optional int64 timestamp = 11;</code>
     *
     * <pre>
     *消息发送时间
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 11;</code>
     *
     * <pre>
     *消息发送时间
     * </pre>
     */
    long getTimestamp();

    /**
     * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
     *
     * <pre>
     *回复消息内容 同消息
     * </pre>
     */
    boolean hasReply();
    /**
     * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
     *
     * <pre>
     *回复消息内容 同消息
     * </pre>
     */
    com.snh.chat.protobuf.ChatMessageProto.ChatMessage getReply();
    /**
     * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
     *
     * <pre>
     *回复消息内容 同消息
     * </pre>
     */
    com.snh.chat.protobuf.ChatMessageProto.ChatMessageOrBuilder getReplyOrBuilder();
  }
  /**
   * Protobuf type {@code com.snh.chat.protobuf.proto.ChatMessage}
   */
  public  static final class ChatMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.snh.chat.protobuf.proto.ChatMessage)
      ChatMessageOrBuilder {
    // Use ChatMessage.newBuilder() to construct.
    private ChatMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ChatMessage() {
      action_ = 0;
      uuid_ = "";
      userId_ = "";
      groupId_ = "";
      nickname_ = "";
      pic_ = "";
      content_ = "";
      pictures_ = "";
      videos_ = "";
      audios_ = "";
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              action_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              uuid_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              userId_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              groupId_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              nickname_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              pic_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              content_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              pictures_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              videos_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              audios_ = bs;
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              timestamp_ = input.readInt64();
              break;
            }
            case 98: {
              com.snh.chat.protobuf.ChatMessageProto.ChatMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000800) == 0x00000800)) {
                subBuilder = reply_.toBuilder();
              }
              reply_ = input.readMessage(com.snh.chat.protobuf.ChatMessageProto.ChatMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(reply_);
                reply_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000800;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.snh.chat.protobuf.ChatMessageProto.internal_static_com_snh_chat_protobuf_proto_ChatMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.snh.chat.protobuf.ChatMessageProto.internal_static_com_snh_chat_protobuf_proto_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.snh.chat.protobuf.ChatMessageProto.ChatMessage.class, com.snh.chat.protobuf.ChatMessageProto.ChatMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ACTION_FIELD_NUMBER = 1;
    private int action_;
    /**
     * <code>optional int32 action = 1;</code>
     *
     * <pre>
     *消息类型 0-普通消息/回复消息 1-系统消息  2-加入群组 3-离开群组
     * </pre>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 action = 1;</code>
     *
     * <pre>
     *消息类型 0-普通消息/回复消息 1-系统消息  2-加入群组 3-离开群组
     * </pre>
     */
    public int getAction() {
      return action_;
    }

    public static final int UUID_FIELD_NUMBER = 2;
    private volatile java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 2;</code>
     *
     * <pre>
     *"S-" + UUID.randomUUID() 系统消息
     *"U-{userId}-{groupId}"+UUID.randomUUID() 用户消息
     * </pre>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string uuid = 2;</code>
     *
     * <pre>
     *"S-" + UUID.randomUUID() 系统消息
     *"U-{userId}-{groupId}"+UUID.randomUUID() 用户消息
     * </pre>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 2;</code>
     *
     * <pre>
     *"S-" + UUID.randomUUID() 系统消息
     *"U-{userId}-{groupId}"+UUID.randomUUID() 用户消息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private volatile java.lang.Object userId_;
    /**
     * <code>optional string userId = 3;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string userId = 3;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userId = 3;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPID_FIELD_NUMBER = 4;
    private volatile java.lang.Object groupId_;
    /**
     * <code>optional string groupId = 4;</code>
     *
     * <pre>
     *群组ID
     * </pre>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string groupId = 4;</code>
     *
     * <pre>
     *群组ID
     * </pre>
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          groupId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string groupId = 4;</code>
     *
     * <pre>
     *群组ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object nickname_;
    /**
     * <code>optional string nickname = 5;</code>
     *
     * <pre>
     *昵称
     * </pre>
     */
    public boolean hasNickname() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string nickname = 5;</code>
     *
     * <pre>
     *昵称
     * </pre>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nickname = 5;</code>
     *
     * <pre>
     *昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PIC_FIELD_NUMBER = 6;
    private volatile java.lang.Object pic_;
    /**
     * <code>optional string pic = 6;</code>
     *
     * <pre>
     *用户头像
     * </pre>
     */
    public boolean hasPic() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string pic = 6;</code>
     *
     * <pre>
     *用户头像
     * </pre>
     */
    public java.lang.String getPic() {
      java.lang.Object ref = pic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pic = 6;</code>
     *
     * <pre>
     *用户头像
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPicBytes() {
      java.lang.Object ref = pic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 7;
    private volatile java.lang.Object content_;
    /**
     * <code>optional string content = 7;</code>
     *
     * <pre>
     *消息文字内容
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string content = 7;</code>
     *
     * <pre>
     *消息文字内容
     * </pre>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 7;</code>
     *
     * <pre>
     *消息文字内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PICTURES_FIELD_NUMBER = 8;
    private volatile java.lang.Object pictures_;
    /**
     * <code>optional string pictures = 8;</code>
     *
     * <pre>
     *图片
     * </pre>
     */
    public boolean hasPictures() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string pictures = 8;</code>
     *
     * <pre>
     *图片
     * </pre>
     */
    public java.lang.String getPictures() {
      java.lang.Object ref = pictures_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pictures_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pictures = 8;</code>
     *
     * <pre>
     *图片
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPicturesBytes() {
      java.lang.Object ref = pictures_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pictures_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VIDEOS_FIELD_NUMBER = 9;
    private volatile java.lang.Object videos_;
    /**
     * <code>optional string videos = 9;</code>
     *
     * <pre>
     *视频
     * </pre>
     */
    public boolean hasVideos() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string videos = 9;</code>
     *
     * <pre>
     *视频
     * </pre>
     */
    public java.lang.String getVideos() {
      java.lang.Object ref = videos_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          videos_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string videos = 9;</code>
     *
     * <pre>
     *视频
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVideosBytes() {
      java.lang.Object ref = videos_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        videos_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUDIOS_FIELD_NUMBER = 10;
    private volatile java.lang.Object audios_;
    /**
     * <code>optional string audios = 10;</code>
     *
     * <pre>
     *音频
     * </pre>
     */
    public boolean hasAudios() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string audios = 10;</code>
     *
     * <pre>
     *音频
     * </pre>
     */
    public java.lang.String getAudios() {
      java.lang.Object ref = audios_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          audios_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string audios = 10;</code>
     *
     * <pre>
     *音频
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAudiosBytes() {
      java.lang.Object ref = audios_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        audios_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 11;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 11;</code>
     *
     * <pre>
     *消息发送时间
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int64 timestamp = 11;</code>
     *
     * <pre>
     *消息发送时间
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int REPLY_FIELD_NUMBER = 12;
    private com.snh.chat.protobuf.ChatMessageProto.ChatMessage reply_;
    /**
     * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
     *
     * <pre>
     *回复消息内容 同消息
     * </pre>
     */
    public boolean hasReply() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
     *
     * <pre>
     *回复消息内容 同消息
     * </pre>
     */
    public com.snh.chat.protobuf.ChatMessageProto.ChatMessage getReply() {
      return reply_ == null ? com.snh.chat.protobuf.ChatMessageProto.ChatMessage.getDefaultInstance() : reply_;
    }
    /**
     * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
     *
     * <pre>
     *回复消息内容 同消息
     * </pre>
     */
    public com.snh.chat.protobuf.ChatMessageProto.ChatMessageOrBuilder getReplyOrBuilder() {
      return reply_ == null ? com.snh.chat.protobuf.ChatMessageProto.ChatMessage.getDefaultInstance() : reply_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, action_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, userId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, groupId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, nickname_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, pic_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, content_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, pictures_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, videos_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, audios_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, timestamp_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeMessage(12, getReply());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, action_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, userId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, groupId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, nickname_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, pic_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, content_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, pictures_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(9, videos_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, audios_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, timestamp_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, getReply());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.snh.chat.protobuf.ChatMessageProto.ChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.snh.chat.protobuf.ChatMessageProto.ChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.snh.chat.protobuf.ChatMessageProto.ChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.snh.chat.protobuf.ChatMessageProto.ChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.snh.chat.protobuf.ChatMessageProto.ChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.snh.chat.protobuf.ChatMessageProto.ChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.snh.chat.protobuf.ChatMessageProto.ChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.snh.chat.protobuf.ChatMessageProto.ChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.snh.chat.protobuf.ChatMessageProto.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.snh.chat.protobuf.ChatMessageProto.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.snh.chat.protobuf.ChatMessageProto.ChatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.snh.chat.protobuf.proto.ChatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.snh.chat.protobuf.proto.ChatMessage)
        com.snh.chat.protobuf.ChatMessageProto.ChatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.snh.chat.protobuf.ChatMessageProto.internal_static_com_snh_chat_protobuf_proto_ChatMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.snh.chat.protobuf.ChatMessageProto.internal_static_com_snh_chat_protobuf_proto_ChatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.snh.chat.protobuf.ChatMessageProto.ChatMessage.class, com.snh.chat.protobuf.ChatMessageProto.ChatMessage.Builder.class);
      }

      // Construct using com.snh.chat.protobuf.ChatMessageProto.ChatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReplyFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        action_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        groupId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        nickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        pic_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        pictures_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        videos_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        audios_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        if (replyBuilder_ == null) {
          reply_ = null;
        } else {
          replyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.snh.chat.protobuf.ChatMessageProto.internal_static_com_snh_chat_protobuf_proto_ChatMessage_descriptor;
      }

      public com.snh.chat.protobuf.ChatMessageProto.ChatMessage getDefaultInstanceForType() {
        return com.snh.chat.protobuf.ChatMessageProto.ChatMessage.getDefaultInstance();
      }

      public com.snh.chat.protobuf.ChatMessageProto.ChatMessage build() {
        com.snh.chat.protobuf.ChatMessageProto.ChatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.snh.chat.protobuf.ChatMessageProto.ChatMessage buildPartial() {
        com.snh.chat.protobuf.ChatMessageProto.ChatMessage result = new com.snh.chat.protobuf.ChatMessageProto.ChatMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.groupId_ = groupId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.nickname_ = nickname_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.pic_ = pic_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.pictures_ = pictures_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.videos_ = videos_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.audios_ = audios_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        if (replyBuilder_ == null) {
          result.reply_ = reply_;
        } else {
          result.reply_ = replyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.snh.chat.protobuf.ChatMessageProto.ChatMessage) {
          return mergeFrom((com.snh.chat.protobuf.ChatMessageProto.ChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.snh.chat.protobuf.ChatMessageProto.ChatMessage other) {
        if (other == com.snh.chat.protobuf.ChatMessageProto.ChatMessage.getDefaultInstance()) return this;
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasUuid()) {
          bitField0_ |= 0x00000002;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasUserId()) {
          bitField0_ |= 0x00000004;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasGroupId()) {
          bitField0_ |= 0x00000008;
          groupId_ = other.groupId_;
          onChanged();
        }
        if (other.hasNickname()) {
          bitField0_ |= 0x00000010;
          nickname_ = other.nickname_;
          onChanged();
        }
        if (other.hasPic()) {
          bitField0_ |= 0x00000020;
          pic_ = other.pic_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000040;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasPictures()) {
          bitField0_ |= 0x00000080;
          pictures_ = other.pictures_;
          onChanged();
        }
        if (other.hasVideos()) {
          bitField0_ |= 0x00000100;
          videos_ = other.videos_;
          onChanged();
        }
        if (other.hasAudios()) {
          bitField0_ |= 0x00000200;
          audios_ = other.audios_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasReply()) {
          mergeReply(other.getReply());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.snh.chat.protobuf.ChatMessageProto.ChatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.snh.chat.protobuf.ChatMessageProto.ChatMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int action_ ;
      /**
       * <code>optional int32 action = 1;</code>
       *
       * <pre>
       *消息类型 0-普通消息/回复消息 1-系统消息  2-加入群组 3-离开群组
       * </pre>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 action = 1;</code>
       *
       * <pre>
       *消息类型 0-普通消息/回复消息 1-系统消息  2-加入群组 3-离开群组
       * </pre>
       */
      public int getAction() {
        return action_;
      }
      /**
       * <code>optional int32 action = 1;</code>
       *
       * <pre>
       *消息类型 0-普通消息/回复消息 1-系统消息  2-加入群组 3-离开群组
       * </pre>
       */
      public Builder setAction(int value) {
        bitField0_ |= 0x00000001;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 action = 1;</code>
       *
       * <pre>
       *消息类型 0-普通消息/回复消息 1-系统消息  2-加入群组 3-离开群组
       * </pre>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 2;</code>
       *
       * <pre>
       *"S-" + UUID.randomUUID() 系统消息
       *"U-{userId}-{groupId}"+UUID.randomUUID() 用户消息
       * </pre>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string uuid = 2;</code>
       *
       * <pre>
       *"S-" + UUID.randomUUID() 系统消息
       *"U-{userId}-{groupId}"+UUID.randomUUID() 用户消息
       * </pre>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 2;</code>
       *
       * <pre>
       *"S-" + UUID.randomUUID() 系统消息
       *"U-{userId}-{groupId}"+UUID.randomUUID() 用户消息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 2;</code>
       *
       * <pre>
       *"S-" + UUID.randomUUID() 系统消息
       *"U-{userId}-{groupId}"+UUID.randomUUID() 用户消息
       * </pre>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 2;</code>
       *
       * <pre>
       *"S-" + UUID.randomUUID() 系统消息
       *"U-{userId}-{groupId}"+UUID.randomUUID() 用户消息
       * </pre>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 2;</code>
       *
       * <pre>
       *"S-" + UUID.randomUUID() 系统消息
       *"U-{userId}-{groupId}"+UUID.randomUUID() 用户消息
       * </pre>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>optional string userId = 3;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string userId = 3;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userId = 3;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userId = 3;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 3;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 3;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object groupId_ = "";
      /**
       * <code>optional string groupId = 4;</code>
       *
       * <pre>
       *群组ID
       * </pre>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string groupId = 4;</code>
       *
       * <pre>
       *群组ID
       * </pre>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            groupId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string groupId = 4;</code>
       *
       * <pre>
       *群组ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string groupId = 4;</code>
       *
       * <pre>
       *群组ID
       * </pre>
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string groupId = 4;</code>
       *
       * <pre>
       *群组ID
       * </pre>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string groupId = 4;</code>
       *
       * <pre>
       *群组ID
       * </pre>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        groupId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <code>optional string nickname = 5;</code>
       *
       * <pre>
       *昵称
       * </pre>
       */
      public boolean hasNickname() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string nickname = 5;</code>
       *
       * <pre>
       *昵称
       * </pre>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nickname = 5;</code>
       *
       * <pre>
       *昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nickname = 5;</code>
       *
       * <pre>
       *昵称
       * </pre>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 5;</code>
       *
       * <pre>
       *昵称
       * </pre>
       */
      public Builder clearNickname() {
        bitField0_ = (bitField0_ & ~0x00000010);
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 5;</code>
       *
       * <pre>
       *昵称
       * </pre>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        nickname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pic_ = "";
      /**
       * <code>optional string pic = 6;</code>
       *
       * <pre>
       *用户头像
       * </pre>
       */
      public boolean hasPic() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string pic = 6;</code>
       *
       * <pre>
       *用户头像
       * </pre>
       */
      public java.lang.String getPic() {
        java.lang.Object ref = pic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pic = 6;</code>
       *
       * <pre>
       *用户头像
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPicBytes() {
        java.lang.Object ref = pic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pic = 6;</code>
       *
       * <pre>
       *用户头像
       * </pre>
       */
      public Builder setPic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        pic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pic = 6;</code>
       *
       * <pre>
       *用户头像
       * </pre>
       */
      public Builder clearPic() {
        bitField0_ = (bitField0_ & ~0x00000020);
        pic_ = getDefaultInstance().getPic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pic = 6;</code>
       *
       * <pre>
       *用户头像
       * </pre>
       */
      public Builder setPicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        pic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 7;</code>
       *
       * <pre>
       *消息文字内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string content = 7;</code>
       *
       * <pre>
       *消息文字内容
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 7;</code>
       *
       * <pre>
       *消息文字内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 7;</code>
       *
       * <pre>
       *消息文字内容
       * </pre>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 7;</code>
       *
       * <pre>
       *消息文字内容
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000040);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 7;</code>
       *
       * <pre>
       *消息文字内容
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        content_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pictures_ = "";
      /**
       * <code>optional string pictures = 8;</code>
       *
       * <pre>
       *图片
       * </pre>
       */
      public boolean hasPictures() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string pictures = 8;</code>
       *
       * <pre>
       *图片
       * </pre>
       */
      public java.lang.String getPictures() {
        java.lang.Object ref = pictures_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pictures_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pictures = 8;</code>
       *
       * <pre>
       *图片
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPicturesBytes() {
        java.lang.Object ref = pictures_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pictures_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pictures = 8;</code>
       *
       * <pre>
       *图片
       * </pre>
       */
      public Builder setPictures(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        pictures_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pictures = 8;</code>
       *
       * <pre>
       *图片
       * </pre>
       */
      public Builder clearPictures() {
        bitField0_ = (bitField0_ & ~0x00000080);
        pictures_ = getDefaultInstance().getPictures();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pictures = 8;</code>
       *
       * <pre>
       *图片
       * </pre>
       */
      public Builder setPicturesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        pictures_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object videos_ = "";
      /**
       * <code>optional string videos = 9;</code>
       *
       * <pre>
       *视频
       * </pre>
       */
      public boolean hasVideos() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string videos = 9;</code>
       *
       * <pre>
       *视频
       * </pre>
       */
      public java.lang.String getVideos() {
        java.lang.Object ref = videos_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            videos_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string videos = 9;</code>
       *
       * <pre>
       *视频
       * </pre>
       */
      public com.google.protobuf.ByteString
          getVideosBytes() {
        java.lang.Object ref = videos_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          videos_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string videos = 9;</code>
       *
       * <pre>
       *视频
       * </pre>
       */
      public Builder setVideos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        videos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string videos = 9;</code>
       *
       * <pre>
       *视频
       * </pre>
       */
      public Builder clearVideos() {
        bitField0_ = (bitField0_ & ~0x00000100);
        videos_ = getDefaultInstance().getVideos();
        onChanged();
        return this;
      }
      /**
       * <code>optional string videos = 9;</code>
       *
       * <pre>
       *视频
       * </pre>
       */
      public Builder setVideosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        videos_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object audios_ = "";
      /**
       * <code>optional string audios = 10;</code>
       *
       * <pre>
       *音频
       * </pre>
       */
      public boolean hasAudios() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string audios = 10;</code>
       *
       * <pre>
       *音频
       * </pre>
       */
      public java.lang.String getAudios() {
        java.lang.Object ref = audios_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            audios_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string audios = 10;</code>
       *
       * <pre>
       *音频
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAudiosBytes() {
        java.lang.Object ref = audios_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          audios_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string audios = 10;</code>
       *
       * <pre>
       *音频
       * </pre>
       */
      public Builder setAudios(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        audios_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string audios = 10;</code>
       *
       * <pre>
       *音频
       * </pre>
       */
      public Builder clearAudios() {
        bitField0_ = (bitField0_ & ~0x00000200);
        audios_ = getDefaultInstance().getAudios();
        onChanged();
        return this;
      }
      /**
       * <code>optional string audios = 10;</code>
       *
       * <pre>
       *音频
       * </pre>
       */
      public Builder setAudiosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        audios_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 11;</code>
       *
       * <pre>
       *消息发送时间
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int64 timestamp = 11;</code>
       *
       * <pre>
       *消息发送时间
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 11;</code>
       *
       * <pre>
       *消息发送时间
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000400;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 11;</code>
       *
       * <pre>
       *消息发送时间
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000400);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.snh.chat.protobuf.ChatMessageProto.ChatMessage reply_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.snh.chat.protobuf.ChatMessageProto.ChatMessage, com.snh.chat.protobuf.ChatMessageProto.ChatMessage.Builder, com.snh.chat.protobuf.ChatMessageProto.ChatMessageOrBuilder> replyBuilder_;
      /**
       * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
       *
       * <pre>
       *回复消息内容 同消息
       * </pre>
       */
      public boolean hasReply() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
       *
       * <pre>
       *回复消息内容 同消息
       * </pre>
       */
      public com.snh.chat.protobuf.ChatMessageProto.ChatMessage getReply() {
        if (replyBuilder_ == null) {
          return reply_ == null ? com.snh.chat.protobuf.ChatMessageProto.ChatMessage.getDefaultInstance() : reply_;
        } else {
          return replyBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
       *
       * <pre>
       *回复消息内容 同消息
       * </pre>
       */
      public Builder setReply(com.snh.chat.protobuf.ChatMessageProto.ChatMessage value) {
        if (replyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reply_ = value;
          onChanged();
        } else {
          replyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      /**
       * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
       *
       * <pre>
       *回复消息内容 同消息
       * </pre>
       */
      public Builder setReply(
          com.snh.chat.protobuf.ChatMessageProto.ChatMessage.Builder builderForValue) {
        if (replyBuilder_ == null) {
          reply_ = builderForValue.build();
          onChanged();
        } else {
          replyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      /**
       * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
       *
       * <pre>
       *回复消息内容 同消息
       * </pre>
       */
      public Builder mergeReply(com.snh.chat.protobuf.ChatMessageProto.ChatMessage value) {
        if (replyBuilder_ == null) {
          if (((bitField0_ & 0x00000800) == 0x00000800) &&
              reply_ != null &&
              reply_ != com.snh.chat.protobuf.ChatMessageProto.ChatMessage.getDefaultInstance()) {
            reply_ =
              com.snh.chat.protobuf.ChatMessageProto.ChatMessage.newBuilder(reply_).mergeFrom(value).buildPartial();
          } else {
            reply_ = value;
          }
          onChanged();
        } else {
          replyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      /**
       * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
       *
       * <pre>
       *回复消息内容 同消息
       * </pre>
       */
      public Builder clearReply() {
        if (replyBuilder_ == null) {
          reply_ = null;
          onChanged();
        } else {
          replyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }
      /**
       * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
       *
       * <pre>
       *回复消息内容 同消息
       * </pre>
       */
      public com.snh.chat.protobuf.ChatMessageProto.ChatMessage.Builder getReplyBuilder() {
        bitField0_ |= 0x00000800;
        onChanged();
        return getReplyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
       *
       * <pre>
       *回复消息内容 同消息
       * </pre>
       */
      public com.snh.chat.protobuf.ChatMessageProto.ChatMessageOrBuilder getReplyOrBuilder() {
        if (replyBuilder_ != null) {
          return replyBuilder_.getMessageOrBuilder();
        } else {
          return reply_ == null ?
              com.snh.chat.protobuf.ChatMessageProto.ChatMessage.getDefaultInstance() : reply_;
        }
      }
      /**
       * <code>optional .com.snh.chat.protobuf.proto.ChatMessage reply = 12;</code>
       *
       * <pre>
       *回复消息内容 同消息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.snh.chat.protobuf.ChatMessageProto.ChatMessage, com.snh.chat.protobuf.ChatMessageProto.ChatMessage.Builder, com.snh.chat.protobuf.ChatMessageProto.ChatMessageOrBuilder> 
          getReplyFieldBuilder() {
        if (replyBuilder_ == null) {
          replyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.snh.chat.protobuf.ChatMessageProto.ChatMessage, com.snh.chat.protobuf.ChatMessageProto.ChatMessage.Builder, com.snh.chat.protobuf.ChatMessageProto.ChatMessageOrBuilder>(
                  getReply(),
                  getParentForChildren(),
                  isClean());
          reply_ = null;
        }
        return replyBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.snh.chat.protobuf.proto.ChatMessage)
    }

    // @@protoc_insertion_point(class_scope:com.snh.chat.protobuf.proto.ChatMessage)
    private static final com.snh.chat.protobuf.ChatMessageProto.ChatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.snh.chat.protobuf.ChatMessageProto.ChatMessage();
    }

    public static com.snh.chat.protobuf.ChatMessageProto.ChatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ChatMessage>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
      public ChatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ChatMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ChatMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessage> getParserForType() {
      return PARSER;
    }

    public com.snh.chat.protobuf.ChatMessageProto.ChatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_snh_chat_protobuf_proto_ChatMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_snh_chat_protobuf_proto_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021chatmessage.proto\022\033com.snh.chat.protob" +
      "uf.proto\"\372\001\n\013ChatMessage\022\016\n\006action\030\001 \001(\005" +
      "\022\014\n\004uuid\030\002 \001(\t\022\016\n\006userId\030\003 \001(\t\022\017\n\007groupI" +
      "d\030\004 \001(\t\022\020\n\010nickname\030\005 \001(\t\022\013\n\003pic\030\006 \001(\t\022\017" +
      "\n\007content\030\007 \001(\t\022\020\n\010pictures\030\010 \001(\t\022\016\n\006vid" +
      "eos\030\t \001(\t\022\016\n\006audios\030\n \001(\t\022\021\n\ttimestamp\030\013" +
      " \001(\003\0227\n\005reply\030\014 \001(\0132(.com.snh.chat.proto" +
      "buf.proto.ChatMessageB)\n\025com.snh.chat.pr" +
      "otobufB\020ChatMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_snh_chat_protobuf_proto_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_snh_chat_protobuf_proto_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_snh_chat_protobuf_proto_ChatMessage_descriptor,
        new java.lang.String[] { "Action", "Uuid", "UserId", "GroupId", "Nickname", "Pic", "Content", "Pictures", "Videos", "Audios", "Timestamp", "Reply", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
